name: ip_geolocation_api
description: A dart package to flutter or dart projects to get your geolocation data from your IP,
version: 0.0.1
homepage: https://github.com/irubenboy/dart-ip-geolocation-api.git

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
